In [3]:
import torch
import numpy as np
import torch.nn as nn
from torch.nn import functional as F 
import time
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [2]:
randint = torch.randint(100,200, (6,))
randint

tensor([161, 193, 127, 145, 150, 189])

In [3]:
tensor = torch.tensor([[1.1,1.3,1.4], [1.5,1.3,1.4], [1.1,1.9,1.4]])
tensor

tensor([[1.1000, 1.3000, 1.4000],
        [1.5000, 1.3000, 1.4000],
        [1.1000, 1.9000, 1.4000]])

In [4]:
zeroes = torch.zeros(3,2, dtype = torch.long)
zeroes

tensor([[0, 0],
        [0, 0],
        [0, 0]])

In [5]:
arange = torch.arange(5)
arange

tensor([0, 1, 2, 3, 4])

In [6]:
linspace = torch.linspace(3,10, steps = 4)
linspace

tensor([ 3.0000,  5.3333,  7.6667, 10.0000])

In [7]:
logspace  = torch.logspace(3,10, steps = 4)
logspace

tensor([1.0000e+03, 2.1544e+05, 4.6416e+07, 1.0000e+10])

In [8]:
eye = torch.eye(5, dtype = torch.long)
eye

tensor([[1, 0, 0, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 0, 1, 0],
        [0, 0, 0, 0, 1]])

In [9]:
a = torch.ones(2,3, dtype = torch.int64)
empty_like = torch.empty_like(a)
empty_like

tensor([[4726955447536,             0,             0],
        [            0,             0,             0]])

In [10]:
start_time = time.time()
zeroes = torch.rand(100,100,100,100).to(device)

end_time = time.time()

start_time1 = time.time()
zeroes1 = torch.rand(100,100,100,100)

end_time1 = time.time()
time_taken = end_time - start_time
time_taken1 = end_time1 - start_time1
print("time taken = ", time_taken)
print("time taken = ", time_taken1)

time taken =  3.6035518646240234
time taken =  1.8442397117614746


In [11]:
#probability sample for num_samples time
probabilities = torch.tensor([0.1,0.9])
samples = torch.multinomial(probabilities, num_samples = 10, replacement = True)
samples

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [12]:
#concatenate
a = torch.tensor([0.1,0.9])
b = torch.tensor([0.4,0.3])
c = torch.cat((a, b), dim = 0)
c

tensor([0.1000, 0.9000, 0.4000, 0.3000])

In [13]:
#triangle lower
out = torch.tril(torch.ones(5,5))
out

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [14]:
#triangle upper
out = torch.triu(torch.ones(5,5))
out

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])

In [15]:
out = torch.zeros(5,5).masked_fill(torch.tril(torch.ones(5,5)) == 0, float('-inf'))
out

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])

In [16]:
out = torch.exp(out)
out

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [17]:
out = torch.rand(10,4)
print(out)
out  =  out.transpose(0,1)
print(out)

tensor([[0.9148, 0.1055, 0.2490, 0.1254],
        [0.9655, 0.3343, 0.7155, 0.2793],
        [0.7906, 0.2991, 0.0114, 0.1615],
        [0.6814, 0.7154, 0.3230, 0.5829],
        [0.4453, 0.9798, 0.0602, 0.3042],
        [0.3041, 0.3797, 0.1766, 0.5000],
        [0.6086, 0.2102, 0.7624, 0.7936],
        [0.1062, 0.0252, 0.5330, 0.8819],
        [0.6898, 0.3869, 0.6812, 0.7812],
        [0.0064, 0.1257, 0.9512, 0.2256]])
tensor([[0.9148, 0.9655, 0.7906, 0.6814, 0.4453, 0.3041, 0.6086, 0.1062, 0.6898,
         0.0064],
        [0.1055, 0.3343, 0.2991, 0.7154, 0.9798, 0.3797, 0.2102, 0.0252, 0.3869,
         0.1257],
        [0.2490, 0.7155, 0.0114, 0.3230, 0.0602, 0.1766, 0.7624, 0.5330, 0.6812,
         0.9512],
        [0.1254, 0.2793, 0.1615, 0.5829, 0.3042, 0.5000, 0.7936, 0.8819, 0.7812,
         0.2256]])


In [18]:
a = torch.tensor([1,2,3])
b = torch.tensor([4,5,6])
c = torch.tensor([7,8,9])
d = torch.stack([a,b,c])
d

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [19]:
import torch.nn as nn
# torch.manual_seed(0)
sample = torch.tensor([10.,10.,10.])
linear = nn.Linear(3,3, bias = False)
print(linear(sample))

tensor([ 0.5974,  0.7684, -7.1363], grad_fn=<SqueezeBackward4>)


In [20]:
import torch.nn.functional as F
sample = torch.tensor([1.,2.,3.])
soft_max = F.softmax(sample,dim=0)
soft_max

tensor([0.0900, 0.2447, 0.6652])

In [21]:
embedding = nn.Embedding(num_embeddings=10, embedding_dim=3)
input_indices = torch.tensor([1, 2, 3, 4 ,6])
embeddings = embedding(input_indices)
print(embeddings)

tensor([[ 0.4647,  0.0821, -0.5067],
        [ 0.5334,  1.2016,  1.2231],
        [ 0.5506,  0.8640, -0.9036],
        [ 0.6654, -0.3413,  1.8612],
        [ 1.6256, -1.1879, -0.8868]], grad_fn=<EmbeddingBackward0>)


In [22]:
tensor1 = torch.tensor([[1.1,1.3,1.4], [1.5,1.3,1.4], [1.1,1.9,1.4]])
tensor2 = torch.tensor([[1.1,1.3,1.4], [1.5,1.3,1.4], [1.1,1.9,1.4]])
d = tensor1 @ tensor2
d

tensor([[4.7000, 5.7800, 5.3200],
        [5.1400, 6.3000, 5.8800],
        [5.6000, 6.5600, 6.1600]])

In [28]:
a = torch.randint(3, (3,2)).float()
a

tensor([[2., 1.],
        [0., 1.],
        [0., 2.]])

In [29]:
b = torch.rand((2,4))
b

tensor([[0.0264, 0.2715, 0.6018, 0.9580],
        [0.8833, 0.0622, 0.2392, 0.3701]])

In [31]:
c = a @ b
c

tensor([[0.9362, 0.6051, 1.4427, 2.2861],
        [0.8833, 0.0622, 0.2392, 0.3701],
        [1.7666, 0.1244, 0.4784, 0.7402]])

In [7]:
m = nn.ReLU()
input = torch.randn(2)
print(m(input))

tensor([0.2849, 0.0000])


In [9]:
input = torch.randn(2)
m = F.sigmoid(input)
print(m)

tensor([0.7678, 0.3550])


In [10]:
input = torch.randn(2)
m = F.tanh(input)
print(m)

tensor([ 0.8028, -0.7669])
